// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum OpClass {
  TRANSFORM = 0,
  REDUCTION = 1,
  MULTIPLICATOR = 2,
  GRAPH = 3,
  CONDITIONAL = 4,
  LOOP = 5
}
