<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Nd4j.Dsp.Runtime.Examples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SdxRuntime.csproj" />
  </ItemGroup>

</Project>
