Likes 0
The following post is from Takeshi Numoto, Corporate Vice President, Cloud and Enterprise Marketing, Microsoft.
Today, Microsoft introduced the Cloud OS Network , a worldwide group of more than 25 leading cloud service providers who have embraced our Cloud OS vision and will deliver hosted services built on the Microsoft Cloud Platform, which includes Windows Server with Hyper-V, System Center and the Windows Azure Pack. This announcement represents important progress against our goals and strategy for Cloud OS . More importantly, it is great news for enterprise customers across the globe.
It’s no secret that cloud computing is a revolution in the world of IT. Companies everywhere, of every size, are looking to capitalize on the cloud, in order to harness big data, manage BYOD and deliver powerful apps to wide range of devices. Ultimately, it’s all about key business drivers like creating new opportunities more quickly, improving employee productivity and lowering costs. Here at Microsoft, we think we’re the best bet for customers because we alone provide a consistent, enterprise-grade platform that is hybrid by design, and one that is based on our experience delivering more than 200 cloud services to billions of people. With the investments and people they already have in place, enterprise customers can tackle big challenges and opportunities of the cloud era using the same Microsoft technologies across their private clouds, the Windows Azure public cloud and service-provider clouds.
Hybrid cloud computing allows customers to make decisions about where to host their applications and data based on business needs, not technology limitations. This makes it possible for organizations to make the most of IT by keeping mission-critical data or applications on-premises, for example, while also accessing almost limitless computing power and storage in the cloud. They can truly enjoy the benefits of datacenters without boundaries.
As one of the fastest-growing segments in the IT industry, cloud service providers play the critical role in our Cloud OS vision. Our overall community of service providers – more than 16,500 infrastructure hosting partners and nearly 10,000 application hosters – is the largest in the industry, and we added 5,000 partners just in the last year.
The members of the Cloud OS Network are leading service providers who will offer hybrid services that give customers greater flexibility and choice. By making a substantial commitment to the Microsoft Cloud Platform, they are able to deliver tailored infrastructure and application services that meet diverse customer needs. Customers will have greater choice in customization, data sovereignty, security, privacy and service levels. For example, Cloud OS Network partner Outsourcery in the United Kingdom is driving an initiative to provide compliant cloud services for U.K. government agencies, as part of its O-Cloud Platform for small, medium and large enterprises.
Together, the Cloud OS Network partners operate in more than 90 countries, serve over 3 million customers every day and manage over 2.4 million servers in more than 425 datacenters. They are all leaders in their geographies and markets, and we are honored by their commitment to support the Cloud OS vision with hybrid solutions for our mutual customers.
Another great example, TeleComputing in Norway and Sweden, delivers more than 2,400 hosted applications to more than 800 businesses. As part of our partnership with them, they are migrating their massive VMware environment to Hyper-V. Tieto, the largest IT services company in Finland, offers the Tieto Productivity Cloud with the goal of making the acquisition of IT resources as simple as Spotify. T-Systems, wholly owned by Deutsche Telekom, is the largest outsourcer in Germany. They are rolling out a new infrastructure-as-a-service offering that will allow large corporate customers to move data from the public cloud to more secure private clouds. SingTel is Asia’s leading telco and ICT group. With their participation in the Cloud OS Network, they will deliver their first truly hybrid offerings, focusing on database-as-a-service, disaster recovery and productivity solutions using Microsoft Lync and Exchange. Here in the U.S., CSC’s cloud services have received top ranking by industry analyst firm Gartner.
If you follow Microsoft and cloud computing, you’ve certainly heard and seen us promote Windows Azure. Our investment and commitment to Azure as a global cloud platform is enormous. But so is our belief in hybrid cloud and that there are going to be many, many clouds around the world due to the tremendous variety of customers and needs. The Cloud OS Network and our partnerships with its members demonstrate our focus on providing choice and flexibility to customers. And it’s all based around the promise of the three connected clouds – private, public and service provider.
