/* ******************************************************************************
 *
 * Generated declarations for the random family CUDA kernels.
 * Definitions live in random_kernels.cu; the executeCuda* selectors in
 * random.cu launch them across translation units.
 *
 * SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/
#ifndef PROJECT_RANDOM_KERNEL_DECLARATIONS_H
#define PROJECT_RANDOM_KERNEL_DECLARATIONS_H

#include <system/common.h>

extern "C" SD_KERNEL void randomSingle_0_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_0_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_0_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_0_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_1_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_1_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_1_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_1_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_2_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_2_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_2_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_2_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_3_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_3_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_3_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_3_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_4_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_4_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_4_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_4_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_5_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_5_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_5_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_5_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_6_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_6_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_6_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_6_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_7_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_7_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_7_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_7_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_8_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_8_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_8_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_8_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_9_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_9_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_9_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_9_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_10_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_10_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_10_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_10_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_11_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_11_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_11_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_11_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_12_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_12_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_12_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_12_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_13_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_13_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_13_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_13_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_14_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_14_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_14_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_14_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_15_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_15_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_15_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_15_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_16_float (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_16_double (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_16_float16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomSingle_16_bfloat16 (sd::Pointer state, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_0_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_0_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_0_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_0_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_1_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_1_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_1_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_1_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_2_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_2_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_2_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_2_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_3_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_3_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_3_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_3_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_4_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_4_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_4_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_4_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_5_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_5_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_5_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_5_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_6_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_6_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_6_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_6_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_7_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_7_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_7_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_7_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_8_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_8_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_8_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_8_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_9_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_9_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_9_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_9_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_10_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_10_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_10_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_10_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_11_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_11_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_11_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_11_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_12_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_12_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_12_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_12_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_13_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_13_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_13_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_13_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_14_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_14_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_14_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_14_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_15_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_15_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_15_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_15_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_16_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_16_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_16_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomDouble_16_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_0_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_0_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_0_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_0_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_1_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_1_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_1_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_1_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_2_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_2_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_2_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_2_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_3_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_3_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_3_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_3_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_4_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_4_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_4_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_4_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_5_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_5_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_5_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_5_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_6_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_6_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_6_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_6_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_7_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_7_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_7_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_7_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_8_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_8_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_8_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_8_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_9_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_9_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_9_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_9_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_10_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_10_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_10_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_10_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_11_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_11_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_11_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_11_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_12_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_12_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_12_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_12_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_13_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_13_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_13_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_13_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_14_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_14_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_14_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_14_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_15_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_15_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_15_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_15_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_16_float (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_16_double (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_16_float16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);
extern "C" SD_KERNEL void randomTriple_16_bfloat16 (sd::Pointer state, void const* x, sd::LongType const* xShapeBuffer, void const* y, sd::LongType const* yShapeBuffer, void* z, sd::LongType const* zShapeBuffer, void* extraArguments);

#endif  // PROJECT_RANDOM_KERNEL_DECLARATIONS_H
