# SPDX-License-Identifier: Apache-2.0
# Run from platform-tests: cmake -DOUTPUT_DIR=/tmp/scalar-generation-test -P test_scalar_cuda_generation.cmake
cmake_minimum_required(VERSION 3.22)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "Provide OUTPUT_DIR for generated test sources")
endif()
list(APPEND CMAKE_MODULE_PATH "${ROOT}/libnd4j/cmake")
include(SelectiveRenderingCore)
include(TemplateProcessing)
set(MULTI_PASS_CHUNK_SIZE 12)
set(UNIFIED_ACTIVE_TYPES BOOL INT8 UINT8 INT16 UINT16 INT32 UINT32 INT64 UINT64 HALF BFLOAT16 FLOAT32 DOUBLE)
set(combinations "")
foreach(i RANGE 0 12)
    list(APPEND combinations "${i},${i},${i}")
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(template_dir "${ROOT}/libnd4j/include/loops/cuda/comb_compilation_units")
foreach(group RANGE 0 3)
    set(generated "")
    if(group EQUAL 0)
        create_direct_instantiation_file("${template_dir}/scalar_instantiation_template_3.cu.in"
            "${combinations}" "${OUTPUT_DIR}" generated)
    else()
        create_direct_instantiation_file_impl("${template_dir}/scalar_group_instantiation_template_3.cu.in"
            "${combinations}" "${OUTPUT_DIR}" generated "scalar_group${group}_instantiation_template_3")
    endif()
    list(LENGTH generated count)
    if(NOT count EQUAL 13)
        message(FATAL_ERROR "Expected 13 dtype units for group ${group}, got ${count}")
    endif()
    foreach(source IN LISTS generated)
        file(READ "${source}" content)
        string(REGEX MATCHALL "template void [^;]+" definitions "${content}")
        list(LENGTH definitions count)
        if(NOT count EQUAL 2)
            message(FATAL_ERROR "Expected two entry points in ${source}, got ${count}")
        endif()
        if(group EQUAL 0)
            string(REGEX MATCHALL "ScalarTransform<[^>]+>" types "${content}")
            list(REMOVE_DUPLICATES types)
            list(LENGTH types count)
            if(NOT count EQUAL 1 OR content MATCHES "Group<")
                message(FATAL_ERROR "Public dispatcher has mixed dtype/helper ownership: ${source}")
            endif()
        else()
            if(content MATCHES "ScalarTransform<" OR NOT content MATCHES "loops/cuda/scalar_group.chpp")
                message(FATAL_ERROR "Helper duplicates public ABI or has wrong implementation: ${source}")
            endif()
            foreach(method executeCudaShapedGroup executeCudaAlongDimensionGroup)
                if(NOT content MATCHES "${method}<${group}, [^>]+>")
                    message(FATAL_ERROR "Missing ${method} specialization in ${source}")
                endif()
            endforeach()
        endif()
    endforeach()
endforeach()
message(STATUS "PASS: 13 public dtype units and 39 operation-group units, two entry points each")
