/* ******************************************************************************
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

#ifndef SD_MLIR_DIALECT_SD_SDDIALECT_H
#define SD_MLIR_DIALECT_SD_SDDIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"

namespace mlir {
namespace sd {

/// SD Dialect namespace
constexpr llvm::StringLiteral kSDDialectNamespace = "sd";

/// SD Data Types matching libnd4j DataType enum
enum class SDDataType : int32_t {
    INHERIT = 0,
    BOOL = 1,
    FLOAT8 = 2,
    HALF = 3,
    FLOAT16 = 3,  // Alias
    BHALF = 4,
    BFLOAT16 = 4,  // Alias
    FLOAT32 = 5,
    DOUBLE = 6,
    INT8 = 7,
    INT16 = 8,
    INT32 = 9,
    INT64 = 10,
    UINT8 = 11,
    UINT16 = 12,
    UINT32 = 13,
    UINT64 = 14,
    QINT8 = 15,
    QINT16 = 16,
    UTF8 = 50,
    UTF16 = 51,
    UTF32 = 52,
    ANY = 100
};

/// Convert MLIR element type to SD data type
SDDataType mlirTypeToSDDataType(Type type);

/// Convert SD data type to MLIR element type
Type sdDataTypeToMLIRType(MLIRContext *ctx, SDDataType dtype);

} // namespace sd
} // namespace mlir

// Include the generated dialect declaration
// This will be generated by TableGen from SDDialect.td
// #include "mlir/dialect/SD/SDDialect.h.inc"

namespace mlir {
namespace sd {

/// SD Dialect - Operations for SameDiff/ND4J computations
class SDDialect : public Dialect {
public:
    explicit SDDialect(MLIRContext *context);

    /// Returns the namespace of the SD dialect
    static llvm::StringRef getDialectNamespace() { return kSDDialectNamespace; }

    /// Hook for materializing constants
    Operation *materializeConstant(OpBuilder &builder, Attribute value,
                                   Type type, Location loc) override;

    /// Parse a type registered to this dialect
    Type parseType(DialectAsmParser &parser) const override;

    /// Print a type registered to this dialect
    void printType(Type type, DialectAsmPrinter &os) const override;
};

} // namespace sd
} // namespace mlir

// Include the generated operation declarations
// This will be generated by TableGen from SDOps.td
// #include "mlir/dialect/SD/SDOps.h.inc"

#endif // SD_MLIR_DIALECT_SD_SDDIALECT_H
