name: Setup for msys2
runs:
  using: composite
  steps:
    - name: Initial install
      shell: cmd
      run: |
           msys2do pacman -S --needed --noconfirm base-devel  git tar pkg-config unzip p7zip zip autoconf autoconf-archive automake patch 
           msys2do pacman -S --needed mingw-w64-x86_64-make --noconfirm  mingw-w64-x86_64-gnupg mingw-w64-x86_64-cmake mingw-w64-x86_64-nasm mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-gcc  mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-SDL mingw-w64-x86_64-ragel mingw-w64-x86_64-sed
           echo '--yes --always-trust' >> ~/.gnupg/gpg.conf
