IF(NOT VEDA_FOUND)
        FIND_PATH       (VEDA_DIR "include/veda.h" PATHS "${CMAKE_CURRENT_LIST_DIR}/../" "/opt/nec/ve/share/veda" "/opt/nec/ve/share/veoffload-veda/")
        FIND_LIBRARY    (VEDA_LIBRARY "libveda.so" "libveda.a" PATHS "${VEDA_DIR}/../../veos/lib64")
        FIND_LIBRARY    (VERA_LIBRARY "libvera.so" "libvera.a" PATHS "${VEDA_DIR}/../../veos/lib64")
        FIND_FILE       (VEDA_DEVICE_LIBRARY "libveda.vso" PATHS "${VEDA_DIR}/../../veos/lib64")
        FIND_PATH       (VEDA_INCLUDES "veda.h" PATHS "${VEDA_DIR}/include")
        SET             (VEDA_FOUND TRUE CACHE BOOL "")
        MARK_AS_ADVANCED(VEDA_DIR VEDA_LIBRARY VEDA_DEVICE_LIBRARY VEDA_INCLUDES VEDA_FOUND)
ENDIF()
