# SmartCcache.cmake - Intelligent ccache integration that respects file changes
#
# Both Windows (via MSYS2 bash) and Linux/macOS use smart_ccache.sh for:
# - Detecting generated files (in BUILD_DIR) and letting ccache use content hashing
# - Tracking source file content hashes to force CCACHE_RECACHE on changes
# - Expanding nvcc --options-file response files inline for ccache visibility

option(SD_SMART_CCACHE "Enable smart ccache wrapper that detects file changes" ON)
option(SD_CCACHE_DEBUG "Enable debug output for smart ccache" OFF)

# Detect Windows robustly by checking if cmd.exe exists, since WIN32/MSVC/CMAKE_HOST_SYSTEM_NAME
# may not be set correctly under MSYS2/MinGW cmake.
set(_SD_IS_WINDOWS FALSE)
if(WIN32 OR MSVC OR CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(_SD_IS_WINDOWS TRUE)
endif()
if(NOT _SD_IS_WINDOWS)
    find_program(_SD_CMD_EXE "cmd.exe")
    if(_SD_CMD_EXE)
        set(_SD_IS_WINDOWS TRUE)
        message(STATUS "Detected Windows via cmd.exe (MSYS2/MinGW environment)")
    endif()
endif()

if(SD_SMART_CCACHE AND CMAKE_CXX_COMPILER_LAUNCHER)
    # Check if the launcher is ccache
    get_filename_component(LAUNCHER_NAME "${CMAKE_CXX_COMPILER_LAUNCHER}" NAME)
    if(LAUNCHER_NAME MATCHES "ccache")
        message(STATUS "Enabling smart ccache wrapper for change detection")

        set(CCACHE_PATH "${CMAKE_CXX_COMPILER_LAUNCHER}")

        # Base directory for hash caches (separate files per architecture)
        set(FILE_HASH_CACHE_DIR "${CMAKE_BINARY_DIR}/.ccache_hashes")
        set(FILE_HASH_LOCK "${CMAKE_BINARY_DIR}/.ccache_file_hashes.lock")
        file(MAKE_DIRECTORY "${FILE_HASH_CACHE_DIR}")

        set(SMART_CCACHE_SCRIPT "${CMAKE_BINARY_DIR}/smart_ccache.sh")

        # Generate wrapper script — used by BOTH Windows (MSYS2 bash) and Linux/macOS
        file(WRITE "${SMART_CCACHE_SCRIPT}" "#!/bin/bash
# Smart ccache wrapper - forces recompile for modified source files
# Generated by CMake SmartCcache.cmake
#
# Strategy:
# - If file is NEW (not in hash cache): let ccache use content-based caching (may hit!)
# - If file is KNOWN and UNCHANGED: let ccache use content-based caching (will hit)
# - If file is KNOWN and CHANGED: force recompile with CCACHE_RECACHE=1

CCACHE=\"${CCACHE_PATH}\"
HASH_CACHE_DIR=\"${FILE_HASH_CACHE_DIR}\"
HASH_LOCK=\"${FILE_HASH_LOCK}\"
BUILD_DIR=\"${CMAKE_BINARY_DIR}\"
DEBUG=${SD_CCACHE_DEBUG}

# Detect Windows/MSYS2 — needed for platform-specific locking and process management
IS_MSYS=0
case \"\$(uname -o 2>/dev/null)\" in
    Msys|Cygwin|MS/Windows) IS_MSYS=1 ;;
esac

# Set sloppiness for all files to ensure cacheability
export CCACHE_SLOPPINESS=\"file_macro,include_file_ctime,include_file_mtime,pch_defines,time_macros,file_stat_matches,clang_index_store,locale,random_seed\"

# ==============================================================================
# Extract compute capability / architecture from command line arguments
# ==============================================================================
extract_cuda_arch() {
    local arch_list=\"\"
    local prev_arg=\"\"

    for arg in \"\$@\"; do
        if [[ \"\$arg\" =~ ^-arch=sm_([0-9]+) ]] || [[ \"\$arg\" =~ ^--gpu-architecture=sm_([0-9]+) ]]; then
            local sm_ver=\"\${BASH_REMATCH[1]}\"
            if [[ -n \"\$arch_list\" ]]; then
                arch_list=\"\${arch_list}_\${sm_ver}\"
            else
                arch_list=\"\$sm_ver\"
            fi
        fi

        if [[ \"\$arg\" =~ code=sm_([0-9]+) ]]; then
            local sm_ver=\"\${BASH_REMATCH[1]}\"
            if [[ ! \"\$arch_list\" =~ (^|_)\${sm_ver}(_|\$) ]]; then
                if [[ -n \"\$arch_list\" ]]; then
                    arch_list=\"\${arch_list}_\${sm_ver}\"
                else
                    arch_list=\"\$sm_ver\"
                fi
            fi
        fi

        if [[ \"\$prev_arg\" == \"-arch\" ]] && [[ \"\$arg\" =~ ^sm_([0-9]+) ]]; then
            local sm_ver=\"\${BASH_REMATCH[1]}\"
            if [[ -n \"\$arch_list\" ]]; then
                arch_list=\"\${arch_list}_\${sm_ver}\"
            else
                arch_list=\"\$sm_ver\"
            fi
        fi

        prev_arg=\"\$arg\"
    done

    echo \"\$arch_list\"
}

CUDA_ARCH=\"\$(extract_cuda_arch \"\$@\")\"

SEGMENT_KEY=\"\${SD_SMART_CCACHE_SEGMENT:-default}\"
SHAPE_KEY=\"\${SD_SMART_CCACHE_SHAPE_KEY:-base}\"
SEGMENT_KEY=\"\${SEGMENT_KEY//[^A-Za-z0-9_.-]/_}\"
SHAPE_KEY=\"\${SHAPE_KEY//[^A-Za-z0-9_.-]/_}\"

if [[ -n \"\$CUDA_ARCH\" ]]; then
    HASH_CACHE=\"\${HASH_CACHE_DIR}/\${SEGMENT_KEY}__\${SHAPE_KEY}__cuda_sm_\${CUDA_ARCH}\"
else
    HASH_CACHE=\"\${HASH_CACHE_DIR}/\${SEGMENT_KEY}__\${SHAPE_KEY}__default\"
fi

if [[ \"\$DEBUG\" == \"ON\" ]]; then
    if [[ -n \"\$CUDA_ARCH\" ]]; then
        echo \"[SMART_CCACHE] CUDA architecture detected: sm_\${CUDA_ARCH}\" >&2
    fi
    echo \"[SMART_CCACHE] Hash cache file: \$HASH_CACHE\" >&2
fi

mkdir -p \"\$HASH_CACHE_DIR\" 2>/dev/null

SOURCE_FILE=\"\"
for arg in \"\$@\"; do
    case \"\$arg\" in
        *.cpp|*.c|*.cc|*.cxx|*.cu|*.C|*.CC|*.CPP|*.CXX|*.CU)
            if [[ -f \"\$arg\" ]]; then
                SOURCE_FILE=\"\$arg\"
                break
            fi
            if [[ ! \"\$arg\" = /* ]] && [[ -f \"\$(pwd)/\$arg\" ]]; then
                SOURCE_FILE=\"\$(pwd)/\$arg\"
                break
            fi
            ;;
    esac
done

# Platform-aware locking: flock on Linux/macOS, mkdir-based on Windows/MSYS2.
# Windows has mandatory file locks — exec 9>\"file\" blocks when another process
# holds an exclusive flock, causing deadlocks even with flock -n.
# mkdir is atomic on all platforms and doesn't require FD manipulation.
acquire_lock() {
    if [[ \$IS_MSYS -eq 1 ]]; then
        # mkdir-based lock: atomic, no FD issues on Windows
        local attempts=0
        while ! mkdir \"\$HASH_LOCK.d\" 2>/dev/null; do
            attempts=\$((attempts + 1))
            if [[ \$attempts -ge 20 ]]; then
                # Stale lock — remove and retry once (process may have died)
                rm -rf \"\$HASH_LOCK.d\" 2>/dev/null
                if ! mkdir \"\$HASH_LOCK.d\" 2>/dev/null; then
                    return 1
                fi
                break
            fi
            # Brief sleep to avoid busy-spin (MSYS2 sleep supports fractions)
            sleep 0.05
        done
        return 0
    else
        # Linux/macOS: flock with non-blocking to avoid deadlocks
        exec 9>\"\$HASH_LOCK\"
        if ! flock -n -x 9 2>/dev/null; then
            exec 9>&-
            return 1
        fi
        return 0
    fi
}

release_lock() {
    if [[ \$IS_MSYS -eq 1 ]]; then
        rm -rf \"\$HASH_LOCK.d\" 2>/dev/null
    else
        exec 9>&-
    fi
}

update_hash_cache() {
    local file=\"\$1\"
    local hash=\"\$2\"

    if ! acquire_lock; then
        return
    fi

    if [[ -f \"\$HASH_CACHE\" ]]; then
        grep -v \"^\$file:\" \"\$HASH_CACHE\" > \"\$HASH_CACHE.tmp\" 2>/dev/null || true
        mv \"\$HASH_CACHE.tmp\" \"\$HASH_CACHE\" 2>/dev/null || true
    fi
    echo \"\$file:\$hash\" >> \"\$HASH_CACHE\"

    release_lock
}

if [[ -n \"\$SOURCE_FILE\" && -f \"\$SOURCE_FILE\" ]]; then
    IS_GENERATED=0
    case \"\$SOURCE_FILE\" in
        \"\$BUILD_DIR\"*)
            IS_GENERATED=1
            ;;
    esac

    if [[ \$IS_GENERATED -eq 1 ]]; then
        if [[ \"\$DEBUG\" == \"ON\" ]]; then
            echo \"[SMART_CCACHE] Generated file, using ccache content hash: \$SOURCE_FILE\" >&2
        fi
    else
        if [[ ! -f \"\$HASH_CACHE\" ]]; then
            # Clean build: hash cache doesn't exist yet. Skip cksum/lock overhead.
            # Just let ccache handle caching. Populate hash for next build.
            if [[ \"\$DEBUG\" == \"ON\" ]]; then
                echo \"[SMART_CCACHE] Clean build (no cache), skipping hash: \$SOURCE_FILE\" >&2
            fi
            if [[ \$IS_MSYS -eq 1 ]]; then
                # Windows/MSYS2: run synchronously — background subshells become
                # orphans after exec replaces this process, accumulating until deadlock.
                CURRENT_HASH=\"\$(cksum \"\$SOURCE_FILE\" 2>/dev/null | cut -d' ' -f1,2)\"
                if [[ -n \"\$CURRENT_HASH\" ]]; then
                    update_hash_cache \"\$SOURCE_FILE\" \"\$CURRENT_HASH\"
                fi
            else
                # Linux/macOS: background is safe — child processes are reaped normally.
                ( CURRENT_HASH=\"\$(cksum \"\$SOURCE_FILE\" 2>/dev/null | cut -d' ' -f1,2)\"
                  if [[ -n \"\$CURRENT_HASH\" ]]; then
                      acquire_lock && {
                          echo \"\$SOURCE_FILE:\$CURRENT_HASH\" >> \"\$HASH_CACHE\"
                          release_lock
                      }
                  fi
                ) &
            fi
        else
            # Subsequent build: hash cache exists. Check for changes.
            STORED_HASH=\"\"
            if acquire_lock; then
                STORED_HASH=\"\$(grep \"^\$SOURCE_FILE:\" \"\$HASH_CACHE\" 2>/dev/null | tail -1 | cut -d: -f2-)\"
                release_lock
            fi

            if [[ -z \"\$STORED_HASH\" ]]; then
                # New file in subsequent build — let ccache handle it, update hash
                if [[ \"\$DEBUG\" == \"ON\" ]]; then
                    echo \"[SMART_CCACHE] New file, using ccache (may hit cache): \$SOURCE_FILE\" >&2
                fi
                if [[ \$IS_MSYS -eq 1 ]]; then
                    # Windows/MSYS2: synchronous to avoid orphaned subshells
                    CURRENT_HASH=\"\$(cksum \"\$SOURCE_FILE\" 2>/dev/null | cut -d' ' -f1,2)\"
                    if [[ -n \"\$CURRENT_HASH\" ]]; then
                        update_hash_cache \"\$SOURCE_FILE\" \"\$CURRENT_HASH\"
                    fi
                else
                    # Linux/macOS: background is safe
                    ( CURRENT_HASH=\"\$(cksum \"\$SOURCE_FILE\" 2>/dev/null | cut -d' ' -f1,2)\"
                      if [[ -n \"\$CURRENT_HASH\" ]]; then
                          update_hash_cache \"\$SOURCE_FILE\" \"\$CURRENT_HASH\"
                      fi
                    ) &
                fi
            else
                CURRENT_HASH=\"\$(cksum \"\$SOURCE_FILE\" 2>/dev/null | cut -d' ' -f1,2)\"
                if [[ \"\$CURRENT_HASH\" != \"\$STORED_HASH\" ]]; then
                    if [[ \"\$DEBUG\" == \"ON\" ]]; then
                        echo \"[SMART_CCACHE] File changed, forcing recompile: \$SOURCE_FILE\" >&2
                    fi
                    export CCACHE_RECACHE=1
                    update_hash_cache \"\$SOURCE_FILE\" \"\$CURRENT_HASH\"
                else
                    if [[ \"\$DEBUG\" == \"ON\" ]]; then
                        echo \"[SMART_CCACHE] Unchanged, cache hit expected: \$SOURCE_FILE\" >&2
                    fi
                fi
            fi
        fi
    fi
fi

# Expand nvcc --options-file response files inline for ccache visibility
EXPANDED_ARGS=()
while [[ \$# -gt 0 ]]; do
    if [[ \"\$1\" == \"--options-file\" && -n \"\$2\" && -f \"\$2\" ]]; then
        while IFS= read -r line || [[ -n \"\$line\" ]]; do
            [[ -z \"\$line\" || \"\$line\" == \\#* ]] && continue
            eval 'for word in '\"\$line\"'; do EXPANDED_ARGS+=(\"\$word\"); done'
        done < \"\$2\"
        if [[ \"\$DEBUG\" == \"ON\" ]]; then
            echo \"[SMART_CCACHE] Expanded --options-file \$2 (\${#EXPANDED_ARGS[@]} args so far)\" >&2
        fi
        shift 2
    else
        EXPANDED_ARGS+=(\"\$1\")
        shift
    fi
done

exec \"\$CCACHE\" \"\${EXPANDED_ARGS[@]}\"
")

        # Make executable
        file(CHMOD "${SMART_CCACHE_SCRIPT}"
             PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
                         GROUP_READ GROUP_EXECUTE
                         WORLD_READ WORLD_EXECUTE)

        # Override the compiler launcher to use our wrapper
        # On Windows, skip smart wrapper entirely — use plain ccache.
        # MSYS2 bash startup overhead (100-500ms per invocation) causes builds to
        # freeze when 8+ parallel compilations each spawn bash. Plain ccache uses
        # content hashing which handles change detection without the wrapper.
        if(_SD_IS_WINDOWS)
            message(STATUS "Smart ccache: disabled on Windows (using plain ccache to avoid MSYS2 bash overhead)")
            set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PATH}" CACHE STRING "" FORCE)
            set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PATH}" CACHE STRING "" FORCE)
            # Do NOT set CMAKE_CUDA_COMPILER_LAUNCHER — nvcc_filter.py handles it
        else()
            set(CMAKE_C_COMPILER_LAUNCHER "${SMART_CCACHE_SCRIPT}" CACHE STRING "" FORCE)
            set(CMAKE_CXX_COMPILER_LAUNCHER "${SMART_CCACHE_SCRIPT}" CACHE STRING "" FORCE)
            # Also set CUDA compiler launcher for nvcc
            set(CMAKE_CUDA_COMPILER_LAUNCHER "${SMART_CCACHE_SCRIPT}" CACHE STRING "" FORCE)
        endif()

        # Store plain ccache path for ExternalProject use (smart_ccache.sh can't
        # be passed as FILEPATH to ExternalProject either, due to .sh skip rules).
        set(SD_PLAIN_CCACHE_PATH "${CCACHE_PATH}" CACHE FILEPATH
            "Plain ccache path for ExternalProject" FORCE)

        message(STATUS "Smart ccache wrapper: ${SMART_CCACHE_SCRIPT}")
        message(STATUS "Smart ccache wrapper enabled for C, CXX, and CUDA compilers")

        # Provide a target to clear ALL hash caches (forces full recompile check)
        add_custom_target(clear_ccache_hashes
            COMMAND ${CMAKE_COMMAND} -E remove_directory "${FILE_HASH_CACHE_DIR}"
            COMMAND ${CMAKE_COMMAND} -E make_directory "${FILE_HASH_CACHE_DIR}"
            COMMENT "Clearing all ccache file hash caches"
        )

        message(STATUS "  Hash cache directory: ${FILE_HASH_CACHE_DIR}")

    endif()
endif()

# Function to force recompile of specific files
function(force_recompile_files)
    if(SD_SMART_CCACHE)
        set(HASH_CACHE_DIR "${CMAKE_BINARY_DIR}/.ccache_hashes")
        foreach(file ${ARGN})
            get_filename_component(abs_file "${file}" ABSOLUTE)
            if(EXISTS "${abs_file}")
                file(GLOB CACHE_FILES "${HASH_CACHE_DIR}/*")
                foreach(cache_file ${CACHE_FILES})
                    execute_process(
                        COMMAND grep -v "^${abs_file}:" "${cache_file}"
                        OUTPUT_FILE "${cache_file}.tmp"
                        ERROR_QUIET
                    )
                    if(EXISTS "${cache_file}.tmp")
                        file(RENAME "${cache_file}.tmp" "${cache_file}")
                    endif()
                endforeach()
                message(STATUS "Forcing recompile (all architectures): ${file}")
            endif()
        endforeach()
    endif()
endfunction()
