/*
 * ******************************************************************************
 *
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/


// automatically generated by the FlatBuffers compiler, do not modify

package org.nd4j.graph;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class UpdaterState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static UpdaterState getRootAsUpdaterState(ByteBuffer _bb) { return getRootAsUpdaterState(_bb, new UpdaterState()); }
  public static UpdaterState getRootAsUpdaterState(ByteBuffer _bb, UpdaterState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UpdaterState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String paramName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer paramNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer paramNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String updaterStateKeys(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int updaterStateKeysLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector updaterStateKeysVector() { return updaterStateKeysVector(new StringVector()); }
  public StringVector updaterStateKeysVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.nd4j.graph.FlatArray updaterStateValues(int j) { return updaterStateValues(new org.nd4j.graph.FlatArray(), j); }
  public org.nd4j.graph.FlatArray updaterStateValues(org.nd4j.graph.FlatArray obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int updaterStateValuesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public org.nd4j.graph.FlatArray.Vector updaterStateValuesVector() { return updaterStateValuesVector(new org.nd4j.graph.FlatArray.Vector()); }
  public org.nd4j.graph.FlatArray.Vector updaterStateValuesVector(org.nd4j.graph.FlatArray.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createUpdaterState(FlatBufferBuilder builder,
      int paramNameOffset,
      int updaterStateKeysOffset,
      int updaterStateValuesOffset) {
    builder.startTable(3);
    UpdaterState.addUpdaterStateValues(builder, updaterStateValuesOffset);
    UpdaterState.addUpdaterStateKeys(builder, updaterStateKeysOffset);
    UpdaterState.addParamName(builder, paramNameOffset);
    return UpdaterState.endUpdaterState(builder);
  }

  public static void startUpdaterState(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addParamName(FlatBufferBuilder builder, int paramNameOffset) { builder.addOffset(0, paramNameOffset, 0); }
  public static void addUpdaterStateKeys(FlatBufferBuilder builder, int updaterStateKeysOffset) { builder.addOffset(1, updaterStateKeysOffset, 0); }
  public static int createUpdaterStateKeysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUpdaterStateKeysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addUpdaterStateValues(FlatBufferBuilder builder, int updaterStateValuesOffset) { builder.addOffset(2, updaterStateValuesOffset, 0); }
  public static int createUpdaterStateValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUpdaterStateValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endUpdaterState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UpdaterState get(int j) { return get(new UpdaterState(), j); }
    public UpdaterState get(UpdaterState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public UpdaterStateT unpack() {
    UpdaterStateT _o = new UpdaterStateT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(UpdaterStateT _o) {
    String _oParamName = paramName();
    _o.setParamName(_oParamName);
    String[] _oUpdaterStateKeys = new String[updaterStateKeysLength()];
    for (int _j = 0; _j < updaterStateKeysLength(); ++_j) {_oUpdaterStateKeys[_j] = updaterStateKeys(_j);}
    _o.setUpdaterStateKeys(_oUpdaterStateKeys);
    org.nd4j.graph.FlatArrayT[] _oUpdaterStateValues = new org.nd4j.graph.FlatArrayT[updaterStateValuesLength()];
    for (int _j = 0; _j < updaterStateValuesLength(); ++_j) {_oUpdaterStateValues[_j] = (updaterStateValues(_j) != null ? updaterStateValues(_j).unpack() : null);}
    _o.setUpdaterStateValues(_oUpdaterStateValues);
  }
  public static int pack(FlatBufferBuilder builder, UpdaterStateT _o) {
    if (_o == null) return 0;
    int _paramName = _o.getParamName() == null ? 0 : builder.createString(_o.getParamName());
    int _updaterStateKeys = 0;
    if (_o.getUpdaterStateKeys() != null) {
      int[] __updaterStateKeys = new int[_o.getUpdaterStateKeys().length];
      int _j = 0;
      for (String _e : _o.getUpdaterStateKeys()) { __updaterStateKeys[_j] = builder.createString(_e); _j++;}
      _updaterStateKeys = createUpdaterStateKeysVector(builder, __updaterStateKeys);
    }
    int _updaterStateValues = 0;
    if (_o.getUpdaterStateValues() != null) {
      int[] __updaterStateValues = new int[_o.getUpdaterStateValues().length];
      int _j = 0;
      for (org.nd4j.graph.FlatArrayT _e : _o.getUpdaterStateValues()) { __updaterStateValues[_j] = org.nd4j.graph.FlatArray.pack(builder, _e); _j++;}
      _updaterStateValues = createUpdaterStateValuesVector(builder, __updaterStateValues);
    }
    return createUpdaterState(
      builder,
      _paramName,
      _updaterStateKeys,
      _updaterStateValues);
  }
}

