// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost_graph.proto

package org.tensorflow.framework;

public interface CostGraphDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.CostGraphDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.CostGraphDef.Node node = 1;</code>
   */
  java.util.List<CostGraphDef.Node>
      getNodeList();
  /**
   * <code>repeated .tensorflow.CostGraphDef.Node node = 1;</code>
   */
  CostGraphDef.Node getNode(int index);
  /**
   * <code>repeated .tensorflow.CostGraphDef.Node node = 1;</code>
   */
  int getNodeCount();
  /**
   * <code>repeated .tensorflow.CostGraphDef.Node node = 1;</code>
   */
  java.util.List<? extends CostGraphDef.NodeOrBuilder>
      getNodeOrBuilderList();
  /**
   * <code>repeated .tensorflow.CostGraphDef.Node node = 1;</code>
   */
  CostGraphDef.NodeOrBuilder getNodeOrBuilder(
          int index);
}
