// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: function.proto

package org.tensorflow.framework;

public interface FunctionDefLibraryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.FunctionDefLibrary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.FunctionDef function = 1;</code>
   */
  java.util.List<FunctionDef>
      getFunctionList();
  /**
   * <code>repeated .tensorflow.FunctionDef function = 1;</code>
   */
  FunctionDef getFunction(int index);
  /**
   * <code>repeated .tensorflow.FunctionDef function = 1;</code>
   */
  int getFunctionCount();
  /**
   * <code>repeated .tensorflow.FunctionDef function = 1;</code>
   */
  java.util.List<? extends FunctionDefOrBuilder>
      getFunctionOrBuilderList();
  /**
   * <code>repeated .tensorflow.FunctionDef function = 1;</code>
   */
  FunctionDefOrBuilder getFunctionOrBuilder(
          int index);

  /**
   * <code>repeated .tensorflow.GradientDef gradient = 2;</code>
   */
  java.util.List<GradientDef>
      getGradientList();
  /**
   * <code>repeated .tensorflow.GradientDef gradient = 2;</code>
   */
  GradientDef getGradient(int index);
  /**
   * <code>repeated .tensorflow.GradientDef gradient = 2;</code>
   */
  int getGradientCount();
  /**
   * <code>repeated .tensorflow.GradientDef gradient = 2;</code>
   */
  java.util.List<? extends GradientDefOrBuilder>
      getGradientOrBuilderList();
  /**
   * <code>repeated .tensorflow.GradientDef gradient = 2;</code>
   */
  GradientDefOrBuilder getGradientOrBuilder(
          int index);
}
