// Targeted by JavaCPP version 1.5.13: DO NOT EDIT THIS FILE

package org.nd4j.dsp.runtime.bindings;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class SdxNative extends org.nd4j.dsp.runtime.presets.SdxRuntimePresets {
    static { Loader.load(); }

// Parsed from dsp/runtime/dsp_runtime_c.h

/* ******************************************************************************
 *
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// #ifndef LIBND4J_DSP_RUNTIME_C_H
// #define LIBND4J_DSP_RUNTIME_C_H

// #include <stddef.h>
// #include <stdint.h>

// #if defined(_WIN32) || defined(__CYGWIN__)
// #if defined(__GNUC__)
// #define SDX_API __attribute__((dllexport))
// #else
// #define SDX_API __declspec(dllexport)
// #endif
// #else
// #if defined(__GNUC__) && __GNUC__ >= 4
// #define SDX_API __attribute__((visibility("default")))
// #else
// #define SDX_API
// #endif
// #endif

// #ifdef __cplusplus
// #endif

@Opaque public static class sdx_runtime_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public sdx_runtime_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_runtime_t(Pointer p) { super(p); }
}
@Opaque public static class sdx_model_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public sdx_model_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_model_t(Pointer p) { super(p); }
}
@Opaque public static class sdx_context_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public sdx_context_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_context_t(Pointer p) { super(p); }
}
@Opaque public static class sdx_generation_session_t extends Pointer {
    /** Empty constructor. Calls {@code super((Pointer)null)}. */
    public sdx_generation_session_t() { super((Pointer)null); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_generation_session_t(Pointer p) { super(p); }
}

/** enum  */
public static final int
  SDX_RUNTIME_ABI_VERSION = 1;

/** enum sdx_status_t */
public static final int
  SDX_STATUS_OK = 0,
  SDX_STATUS_INVALID_ARGUMENT = 1,
  SDX_STATUS_INCOMPATIBLE_ABI = 2,
  SDX_STATUS_MODEL_LOAD_FAILED = 3,
  SDX_STATUS_EXECUTION_FAILED = 4,
  SDX_STATUS_BACKEND_UNAVAILABLE = 5,
  SDX_STATUS_IO_ERROR = 6,
  SDX_STATUS_UNSUPPORTED = 7;

/** enum sdx_generation_finish_reason_t */
public static final int
  SDX_GENERATION_FINISH_NONE = 0,
  SDX_GENERATION_FINISH_MAX_TOKENS = 1,
  SDX_GENERATION_FINISH_EOS = 2,
  SDX_GENERATION_FINISH_CANCELLED = 3,
  SDX_GENERATION_FINISH_CONTEXT_LIMIT = 4;

/** enum sdx_backend_t */
public static final int
  SDX_BACKEND_AUTO = 0,
  SDX_BACKEND_SLOT_BY_SLOT = 1,
  SDX_BACKEND_CUDA_GRAPHS = 2,
  SDX_BACKEND_NVRTC = 3,
  SDX_BACKEND_PTX = 4,
  SDX_BACKEND_TRITON = 5,
  SDX_BACKEND_MLX = 6,
  SDX_BACKEND_ARM_HYBRID = 7,
  SDX_BACKEND_NNAPI = 8,
  SDX_BACKEND_HIP_GRAPHS = 9,
  SDX_BACKEND_LEVEL_ZERO = 10,
  SDX_BACKEND_VULKAN = 11,
  SDX_BACKEND_METAL = 12,
  SDX_BACKEND_TPU = 13,
  SDX_BACKEND_HEXAGON = 14,
  SDX_BACKEND_OPENVINO = 15;

/** enum sdx_device_type_t */
public static final int
  SDX_DEVICE_HOST = 0,
  SDX_DEVICE_CUDA = 1,
  SDX_DEVICE_AMD = 2;

/** enum sdx_gpu_target_t */
public static final int
  SDX_GPU_TARGET_AUTO = 0,
  SDX_GPU_TARGET_CUDA = 1,
  SDX_GPU_TARGET_AMD = 2,
  SDX_GPU_TARGET_VULKAN = 3,
  SDX_GPU_TARGET_METAL = 4;

public static class sdx_runtime_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_runtime_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_runtime_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_runtime_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_runtime_options_t position(long position) {
        return (sdx_runtime_options_t)super.position(position);
    }
    @Override public sdx_runtime_options_t getPointer(long i) {
        return new sdx_runtime_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_runtime_options_t struct_size(int setter);
}

public static class sdx_model_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_model_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_model_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_model_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_model_options_t position(long position) {
        return (sdx_model_options_t)super.position(position);
    }
    @Override public sdx_model_options_t getPointer(long i) {
        return new sdx_model_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_model_options_t struct_size(int setter);
  public native @Cast("int32_t") int backend(); public native sdx_model_options_t backend(int setter);
  public native @Cast("int32_t") int strict_backend(); public native sdx_model_options_t strict_backend(int setter);
  /* 0 forbids all backend code generation. Hardware backends must then carry
   * their validated bundle assets (for example compiledArtifacts.vulkanSpirv
   * or compiledArtifacts.hexagonKernels); an artifact miss is a hard failure. */
  public native @Cast("int32_t") int allow_runtime_jit(); public native sdx_model_options_t allow_runtime_jit(int setter);
  public native @Cast("int32_t") int gpu_target(); public native sdx_model_options_t gpu_target(int setter);
  /* App-owned writable directory for persistent device/compiler artifacts.
   * sdxLoadBundle copies this path before returning; callers retain ownership. */
  public native @Cast("const char*") BytePointer device_compilation_cache_directory(); public native sdx_model_options_t device_compilation_cache_directory(BytePointer setter);
}

public static class sdx_context_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_context_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_context_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_context_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_context_options_t position(long position) {
        return (sdx_context_options_t)super.position(position);
    }
    @Override public sdx_context_options_t getPointer(long i) {
        return new sdx_context_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_context_options_t struct_size(int setter);
  /** When non-zero, constants and variables loaded from the model bundle are
   * bound by the runtime and omitted from the public context input list.
   * This is the inference/mobile mode: sdxGetNumInputs() then reports only
   * placeholders or other values not present in the bundle. */
  public native @Cast("int32_t") int bind_model_parameters(); public native sdx_context_options_t bind_model_parameters(int setter);
}

public static class sdx_run_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_run_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_run_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_run_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_run_options_t position(long position) {
        return (sdx_run_options_t)super.position(position);
    }
    @Override public sdx_run_options_t getPointer(long i) {
        return new sdx_run_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_run_options_t struct_size(int setter);
  public native @Cast("int32_t") int backend(); public native sdx_run_options_t backend(int setter);
  public native @Cast("int32_t") int strict_signature(); public native sdx_run_options_t strict_signature(int setter);
  public native @Cast("int32_t") int gpu_target(); public native sdx_run_options_t gpu_target(int setter);
}

/**
 * Options for the reusable token-generation session. The session reads its
 * explicit I/O names, KV layout, token IDs, and fixed mobile shape envelope
 * from the bundle's text-generation metadata. Runtime discovery heuristics are
 * deliberately not part of this API.
 */
public static class sdx_generation_session_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_generation_session_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_generation_session_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_generation_session_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_generation_session_options_t position(long position) {
        return (sdx_generation_session_options_t)super.position(position);
    }
    @Override public sdx_generation_session_options_t getPointer(long i) {
        return new sdx_generation_session_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_generation_session_options_t struct_size(int setter);
  /** One physical plan/buffer capacity. Zero uses limits.maxPrefillLength. */
  public native @Cast("int32_t") int fixed_context_capacity(); public native sdx_generation_session_options_t fixed_context_capacity(int setter);
}

/**
 * Scalar generation policy consumed by the shared TokenSampleConfig primitive.
 * Zero-initialize, set struct_size, then override fields as required. A
 * temperature <= 0 selects greedy decoding. top_p <= 0 or >= 1 disables
 * nucleus filtering; repetition_penalty <= 0 is normalized to 1.
 */
public static class sdx_generation_options_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_generation_options_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_generation_options_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_generation_options_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_generation_options_t position(long position) {
        return (sdx_generation_options_t)super.position(position);
    }
    @Override public sdx_generation_options_t getPointer(long i) {
        return new sdx_generation_options_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_generation_options_t struct_size(int setter);
  public native @Cast("int32_t") int max_new_tokens(); public native sdx_generation_options_t max_new_tokens(int setter);
  public native @Cast("int32_t") int min_new_tokens(); public native sdx_generation_options_t min_new_tokens(int setter);
  public native double temperature(); public native sdx_generation_options_t temperature(double setter);
  public native @Cast("int32_t") int top_k(); public native sdx_generation_options_t top_k(int setter);
  public native double top_p(); public native sdx_generation_options_t top_p(double setter);
  public native double min_p(); public native sdx_generation_options_t min_p(double setter);
  public native double repetition_penalty(); public native sdx_generation_options_t repetition_penalty(double setter);
  public native double frequency_penalty(); public native sdx_generation_options_t frequency_penalty(double setter);
  public native double presence_penalty(); public native sdx_generation_options_t presence_penalty(double setter);
  public native double typical_p(); public native sdx_generation_options_t typical_p(double setter);
  public native double xtc_probability(); public native sdx_generation_options_t xtc_probability(double setter);
  public native double xtc_threshold(); public native sdx_generation_options_t xtc_threshold(double setter);
  public native @Cast("int64_t") long seed(); public native sdx_generation_options_t seed(long setter);
}

/** Called synchronously after a token has been committed to session state. */
public static class sdx_token_callback_t extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    sdx_token_callback_t(Pointer p) { super(p); }
    protected sdx_token_callback_t() { allocate(); }
    private native void allocate();
    public native void call(@Cast("int64_t") long token_id, Pointer user_data);
}

/** Return non-zero to request cancellation at the next coherent token boundary. */
public static class sdx_cancel_callback_t extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    sdx_cancel_callback_t(Pointer p) { super(p); }
    protected sdx_cancel_callback_t() { allocate(); }
    private native void allocate();
    public native @Cast("int32_t") int call(Pointer user_data);
}

public static class sdx_generation_callbacks_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_generation_callbacks_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_generation_callbacks_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_generation_callbacks_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_generation_callbacks_t position(long position) {
        return (sdx_generation_callbacks_t)super.position(position);
    }
    @Override public sdx_generation_callbacks_t getPointer(long i) {
        return new sdx_generation_callbacks_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_generation_callbacks_t struct_size(int setter);
  public native sdx_token_callback_t on_token(); public native sdx_generation_callbacks_t on_token(sdx_token_callback_t setter);
  public native sdx_cancel_callback_t should_cancel(); public native sdx_generation_callbacks_t should_cancel(sdx_cancel_callback_t setter);
  public native Pointer user_data(); public native sdx_generation_callbacks_t user_data(Pointer setter);
}

public static class sdx_generation_report_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_generation_report_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_generation_report_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_generation_report_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_generation_report_t position(long position) {
        return (sdx_generation_report_t)super.position(position);
    }
    @Override public sdx_generation_report_t getPointer(long i) {
        return new sdx_generation_report_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_generation_report_t struct_size(int setter);
  public native @Cast("int32_t") int finish_reason(); public native sdx_generation_report_t finish_reason(int setter);
  public native @Cast("int32_t") int prompt_token_count(); public native sdx_generation_report_t prompt_token_count(int setter);
  public native @Cast("int32_t") int generated_token_count(); public native sdx_generation_report_t generated_token_count(int setter);
  public native @Cast("int32_t") int total_generated_token_count(); public native sdx_generation_report_t total_generated_token_count(int setter);
  public native @Cast("int32_t") int context_position(); public native sdx_generation_report_t context_position(int setter);
  public native @Cast("uint64_t") long elapsed_time_ns(); public native sdx_generation_report_t elapsed_time_ns(long setter);
  public native @Cast("uint64_t") long prefill_time_ns(); public native sdx_generation_report_t prefill_time_ns(long setter);
  public native @Cast("uint64_t") long decode_time_ns(); public native sdx_generation_report_t decode_time_ns(long setter);
  public native double decode_tokens_per_second(); public native sdx_generation_report_t decode_tokens_per_second(double setter);
  /** Non-zero when backend evidence was read from the executed decode context. */
  public native @Cast("int32_t") int backend_report_available(); public native sdx_generation_report_t backend_report_available(int setter);
  public native @Cast("int32_t") int requested_backend(); public native sdx_generation_report_t requested_backend(int setter);
  public native @Cast("int32_t") int applied_backend(); public native sdx_generation_report_t applied_backend(int setter);
  public native @Cast("int32_t") int backend_status_code(); public native sdx_generation_report_t backend_status_code(int setter);
  /** 1 = host/capture fallback observed, 0 = requested path, -1 = unknown. */
  public native @Cast("int32_t") int used_fallback(); public native sdx_generation_report_t used_fallback(int setter);
  public native @Cast("int32_t") int requested_gpu_target(); public native sdx_generation_report_t requested_gpu_target(int setter);
  public native @Cast("int32_t") int applied_gpu_target(); public native sdx_generation_report_t applied_gpu_target(int setter);
  public native @Cast("int32_t") int plan_phase(); public native sdx_generation_report_t plan_phase(int setter);
  public native @Cast("int32_t") int execution_count(); public native sdx_generation_report_t execution_count(int setter);
}

public static class sdx_tensor_view_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_tensor_view_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_tensor_view_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_tensor_view_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_tensor_view_t position(long position) {
        return (sdx_tensor_view_t)super.position(position);
    }
    @Override public sdx_tensor_view_t getPointer(long i) {
        return new sdx_tensor_view_t((Pointer)this).offsetAddress(i);
    }

  public native Pointer data(); public native sdx_tensor_view_t data(Pointer setter);
  public native @Cast("const int64_t*") LongPointer shape(); public native sdx_tensor_view_t shape(LongPointer setter);
  public native @Cast("int32_t") int rank(); public native sdx_tensor_view_t rank(int setter);
  public native @Cast("int32_t") int dtype(); public native sdx_tensor_view_t dtype(int setter);
  public native @Cast("size_t") long bytes(); public native sdx_tensor_view_t bytes(long setter);
  public native @Cast("int32_t") int device_type(); public native sdx_tensor_view_t device_type(int setter);
  /* For CUDA/AMD tensors, device_id must be >= 0. Mixed device_ids are
   * supported — the runtime elects the majority device and migrates
   * off-device inputs automatically. Constant replicas are cached. */
  public native @Cast("int32_t") int device_id(); public native sdx_tensor_view_t device_id(int setter);
}

public static class sdx_execution_report_t extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public sdx_execution_report_t() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public sdx_execution_report_t(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public sdx_execution_report_t(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public sdx_execution_report_t position(long position) {
        return (sdx_execution_report_t)super.position(position);
    }
    @Override public sdx_execution_report_t getPointer(long i) {
        return new sdx_execution_report_t((Pointer)this).offsetAddress(i);
    }

  public native @Cast("uint32_t") int struct_size(); public native sdx_execution_report_t struct_size(int setter);
  public native @Cast("int32_t") int requested_backend(); public native sdx_execution_report_t requested_backend(int setter);
  /** Backend read back from the plan after execution (reflects clamping and
   *  plan-side mode changes; sdx_backend_t values). */
  public native @Cast("int32_t") int applied_backend(); public native sdx_execution_report_t applied_backend(int setter);
  public native @Cast("int32_t") int status_code(); public native sdx_execution_report_t status_code(int setter);
  /** 1 = fallback observed (a segment failed graph capture, or the plan is
   *  REPLAY_BLOCKED); 0 = requested/optimal path in force; -1 = unknown
   *  (no execution yet). */
  public native @Cast("int32_t") int used_fallback(); public native sdx_execution_report_t used_fallback(int setter);
  public native @Cast("uint64_t") long execution_time_ns(); public native sdx_execution_report_t execution_time_ns(long setter);
  public native @Cast("int32_t") int requested_gpu_target(); public native sdx_execution_report_t requested_gpu_target(int setter);
  public native @Cast("int32_t") int applied_gpu_target(); public native sdx_execution_report_t applied_gpu_target(int setter);
  /** Plan phase after execution: 0=SLOT_BY_SLOT (warmup), 1=SHAPES_FROZEN, 2=REPLAYING, 3=REPLAY_BLOCKED */
  public native @Cast("int32_t") int plan_phase(); public native sdx_execution_report_t plan_phase(int setter);
  /** Number of executions completed on this context */
  public native @Cast("int32_t") int execution_count(); public native sdx_execution_report_t execution_count(int setter);
}

public static native int sdxGetRuntimeAbiVersion();

public static native @Cast("sdx_status_t") int sdxCreateRuntime(@Const sdx_runtime_options_t options, @Cast("sdx_runtime_t**") PointerPointer out_runtime);
public static native @Cast("sdx_status_t") int sdxCreateRuntime(@Const sdx_runtime_options_t options, @ByPtrPtr sdx_runtime_t out_runtime);
public static native void sdxDestroyRuntime(sdx_runtime_t runtime);

/**
 * Configure, record, clear, and persist diagnostics owned by the selected SDX
 * backend library. These functions intentionally live on the backend-neutral
 * SDX transport: an Android accelerator process may also contain an embedded
 * CPU backend, but only the selected provider owns the active compiled plan
 * and its diagnostic ring.
 *
 * category_mask/category use the DspDiagCategory bit assignments and level is
 * 0=summary, 1=detailed, or 2=full. An empty json_path disables file output.
 */
public static native @Cast("sdx_status_t") int sdxConfigureDiagnostics(
    sdx_runtime_t runtime,
    @Cast("uint32_t") int category_mask,
    @Cast("int32_t") int level,
    @Cast("const char*") BytePointer json_path);
public static native @Cast("sdx_status_t") int sdxConfigureDiagnostics(
    sdx_runtime_t runtime,
    @Cast("uint32_t") int category_mask,
    @Cast("int32_t") int level,
    String json_path);
public static native @Cast("sdx_status_t") int sdxRecordDiagnosticEvent(
    sdx_runtime_t runtime,
    @Cast("uint32_t") int category,
    @Cast("const char*") BytePointer message);
public static native @Cast("sdx_status_t") int sdxRecordDiagnosticEvent(
    sdx_runtime_t runtime,
    @Cast("uint32_t") int category,
    String message);
public static native void sdxClearDiagnostics();
public static native void sdxFlushDiagnostics();

public static native @Cast("sdx_status_t") int sdxLoadBundle(
    sdx_runtime_t runtime,
    @Cast("const char*") BytePointer bundle_path,
    @Const sdx_model_options_t options,
    @Cast("sdx_model_t**") PointerPointer out_model);
public static native @Cast("sdx_status_t") int sdxLoadBundle(
    sdx_runtime_t runtime,
    @Cast("const char*") BytePointer bundle_path,
    @Const sdx_model_options_t options,
    @ByPtrPtr sdx_model_t out_model);
public static native @Cast("sdx_status_t") int sdxLoadBundle(
    sdx_runtime_t runtime,
    String bundle_path,
    @Const sdx_model_options_t options,
    @ByPtrPtr sdx_model_t out_model);
public static native void sdxUnloadModel(sdx_model_t model);

/**
 * Resolved offline text-generation asset paths from the loaded bundle. The
 * returned pointers are owned by the model and stay valid until
 * sdxUnloadModel(). NULL means the manifest did not declare that asset.
 */
public static native @Cast("const char*") BytePointer sdxGetTokenizerPath(@Const sdx_model_t model);
public static native @Cast("const char*") BytePointer sdxGetTextGenerationConfigPath(@Const sdx_model_t model);

/**
 * Create a reusable, metadata-driven generation session over a loaded model.
 * The model must outlive the session. Supported mobile profiles are
 * causal-lm-in-graph-kv-v1 and causal-lm-in-graph-state-v2: batch 1, fixed
 * prefill/decode envelopes, BSHD KV, plan-owned in-graph KV writes, and
 * metadata-declared recurrent state feedback for v2. Unsupported profiles fail
 * explicitly.
 */
public static native @Cast("sdx_status_t") int sdxCreateGenerationSession(
    sdx_model_t model,
    @Const sdx_generation_session_options_t options,
    @Cast("sdx_generation_session_t**") PointerPointer out_session);
public static native @Cast("sdx_status_t") int sdxCreateGenerationSession(
    sdx_model_t model,
    @Const sdx_generation_session_options_t options,
    @ByPtrPtr sdx_generation_session_t out_session);
/** Effective fixed physical capacity after model-envelope clamping. */
public static native @Cast("int32_t") int sdxGetGenerationContextCapacity(
    @Const sdx_generation_session_t session);
public static native void sdxDestroyGenerationSession(sdx_generation_session_t session);

/**
 * Clear logical prompt/KV/recurrent state while retaining the session's sole
 * precompiled context, fixed buffers, and plan.
 */
public static native @Cast("sdx_status_t") int sdxResetGenerationSession(
    sdx_generation_session_t session);

/**
 * Cooperatively cancel an in-flight generation from another thread. The native
 * decode loop observes cancellation between complete token commits, leaving the
 * session safe to continue.
 */
public static native void sdxCancelGeneration(sdx_generation_session_t session);

/**
 * Reset logical state, ingest a rolling prompt window through the precompiled
 * fixed plan, and generate to EOS/cancellation/context capacity. Tokens are returned in
 * out_token_ids and optionally streamed through callbacks on the calling
 * thread. out_capacity must be at least max_new_tokens when out_token_ids is
 * non-NULL; out_count is always required.
 */
public static native @Cast("sdx_status_t") int sdxGenerationGenerate(
    sdx_generation_session_t session,
    @Cast("const int64_t*") LongPointer prompt_token_ids,
    @Cast("int32_t") int num_prompt_tokens,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") LongPointer out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") IntPointer out_count,
    sdx_generation_report_t out_report);
public static native @Cast("sdx_status_t") int sdxGenerationGenerate(
    sdx_generation_session_t session,
    @Cast("const int64_t*") LongBuffer prompt_token_ids,
    @Cast("int32_t") int num_prompt_tokens,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") LongBuffer out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") IntBuffer out_count,
    sdx_generation_report_t out_report);
public static native @Cast("sdx_status_t") int sdxGenerationGenerate(
    sdx_generation_session_t session,
    @Cast("const int64_t*") long[] prompt_token_ids,
    @Cast("int32_t") int num_prompt_tokens,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") long[] out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") int[] out_count,
    sdx_generation_report_t out_report);

/**
 * Continue from the last coherent token/KV boundary without re-prefill. The
 * same output, callback, cancellation, and reporting contract as
 * sdxGenerationGenerate applies.
 */
public static native @Cast("sdx_status_t") int sdxGenerationContinue(
    sdx_generation_session_t session,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") LongPointer out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") IntPointer out_count,
    sdx_generation_report_t out_report);
public static native @Cast("sdx_status_t") int sdxGenerationContinue(
    sdx_generation_session_t session,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") LongBuffer out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") IntBuffer out_count,
    sdx_generation_report_t out_report);
public static native @Cast("sdx_status_t") int sdxGenerationContinue(
    sdx_generation_session_t session,
    @Const sdx_generation_options_t options,
    @Const sdx_generation_callbacks_t callbacks,
    @Cast("int64_t*") long[] out_token_ids,
    @Cast("int32_t") int out_capacity,
    @Cast("int32_t*") int[] out_count,
    sdx_generation_report_t out_report);

/**
 * Create a context using the legacy all-external-input contract. The model
 * must outlive every context created from it.
 */
public static native @Cast("sdx_status_t") int sdxCreateContext(
    sdx_model_t model,
    @Cast("const char*const*") PointerPointer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @Cast("sdx_context_t**") PointerPointer out_context);
public static native @Cast("sdx_status_t") int sdxCreateContext(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr BytePointer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @ByPtrPtr sdx_context_t out_context);
public static native @Cast("sdx_status_t") int sdxCreateContext(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr ByteBuffer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @ByPtrPtr sdx_context_t out_context);
public static native @Cast("sdx_status_t") int sdxCreateContext(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr byte[] requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @ByPtrPtr sdx_context_t out_context);

/**
 * Create a context with explicit input-binding behavior. Setting
 * bind_model_parameters=1 binds constants and variables owned by the loaded
 * bundle internally, leaving only runtime placeholders as public inputs. This
 * is the recommended inference API for mobile and offline applications.
 *
 * This is additive to ABI v1: sdxCreateContext() retains its original behavior.
 * The model must outlive every context created from it.
 */
public static native @Cast("sdx_status_t") int sdxCreateContextWithOptions(
    sdx_model_t model,
    @Cast("const char*const*") PointerPointer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @Const sdx_context_options_t options,
    @Cast("sdx_context_t**") PointerPointer out_context);
public static native @Cast("sdx_status_t") int sdxCreateContextWithOptions(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr BytePointer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @Const sdx_context_options_t options,
    @ByPtrPtr sdx_context_t out_context);
public static native @Cast("sdx_status_t") int sdxCreateContextWithOptions(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr ByteBuffer requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @Const sdx_context_options_t options,
    @ByPtrPtr sdx_context_t out_context);
public static native @Cast("sdx_status_t") int sdxCreateContextWithOptions(
    sdx_model_t model,
    @Cast("const char*const*") @ByPtrPtr byte[] requested_output_names,
    @Cast("int32_t") int num_requested_outputs,
    @Const sdx_context_options_t options,
    @ByPtrPtr sdx_context_t out_context);
public static native void sdxDestroyContext(sdx_context_t context);

public static native @Cast("sdx_status_t") int sdxRun(
    sdx_context_t context,
    @Const sdx_tensor_view_t inputs,
    @Cast("int32_t") int num_inputs,
    @Const sdx_tensor_view_t outputs,
    @Cast("int32_t") int num_outputs,
    @Const sdx_run_options_t options);

/**
 * Execute without caller-allocated output buffers. This is the recommended
 * path for dynamic-shape inference such as autoregressive logits. After a
 * successful call, use sdxGetOutputTensor() to obtain each output.
 */
public static native @Cast("sdx_status_t") int sdxRunAllocating(
    sdx_context_t context,
    @Const sdx_tensor_view_t inputs,
    @Cast("int32_t") int num_inputs,
    @Const sdx_run_options_t options);

public static native @Cast("const char*") BytePointer sdxGetLastError(@Const sdx_runtime_t runtime);
public static native @Cast("sdx_status_t") int sdxGetExecutionReport(
    @Const sdx_context_t context,
    sdx_execution_report_t out_report);

/**
 * Mark an external input index as a VARIABLE (changes value between runs but
 * keeps the same shape). This enables D2D staging buffers for that input.
 * Call after sdxCreateContext(), before the first sdxRun().
 */
public static native @Cast("sdx_status_t") int sdxMarkInputVariable(sdx_context_t context, @Cast("int32_t") int input_index);

/**
 * Mark an external input index as a PLACEHOLDER (changes both value and
 * potentially shape between runs). Placeholders always get H2D sync.
 * Call after sdxCreateContext(), before the first sdxRun().
 */
public static native @Cast("sdx_status_t") int sdxMarkInputPlaceholder(sdx_context_t context, @Cast("int32_t") int input_index);

/**
 * Freeze shapes on the plan. After freezing, all shapes are assumed constant,
 * enabling CUDA graph capture and the argTableStable fast path.
 * Typically called after a warmup phase (a few sdxRun() calls to stabilize shapes).
 */
public static native @Cast("sdx_status_t") int sdxFreezeShapes(sdx_context_t context);

/**
 * Query the current plan phase.
 * Returns: 0=SLOT_BY_SLOT (warmup), 1=SHAPES_FROZEN, 2=REPLAYING,
 * 3=REPLAY_BLOCKED, -1 on error.
 */
public static native @Cast("int32_t") int sdxGetPlanPhase(@Const sdx_context_t context);

/**
 * Return a JSON array describing the functional-replay segments owned by this
 * context's compiled plan. Each entry includes its inclusive start/end op
 * indices, shape key, capture/replay status, execution counts, and op counts.
 *
 * The returned pointer is thread-local and remains valid until the next call
 * to this function on the same thread. Returns NULL for an invalid context or
 * a context without a compiled plan.
 */
public static native @Cast("const char*") BytePointer sdxGetPlanSegmentsSummaryJson(
    @Const sdx_context_t context);

/**
 * Get the number of executions completed on this context.
 */
public static native @Cast("int32_t") int sdxGetExecutionCount(@Const sdx_context_t context);

/**
 * Number of public inputs this context expects per sdxRun() call. For a
 * legacy context this covers constants, variables, and placeholders. For a
 * parameter-bound context it excludes values owned by the loaded bundle and
 * normally contains only placeholders. Returns -1 on error.
 */
public static native @Cast("int32_t") int sdxGetNumInputs(@Const sdx_context_t context);

/**
 * Number of output tensors the plan produces per sdxRun() call.
 * Returns -1 on error.
 */
public static native @Cast("int32_t") int sdxGetNumOutputs(@Const sdx_context_t context);

/**
 * Name of the public input at the given context index. Use together with
 * sdxGetNumInputs() to discover the required input binding order. In a
 * parameter-bound context, bundle-owned weights are not present. The returned
 * pointer stays valid for the context lifetime.
 * Returns NULL for invalid arguments or out-of-range indices.
 */
public static native @Cast("const char*") BytePointer sdxGetInputName(@Const sdx_context_t context, @Cast("int32_t") int input_index);

/**
 * Requested output name at the given context index. The returned pointer stays
 * valid for the context lifetime. Returns NULL when the output was not created
 * from an explicit requested name, or for an invalid index.
 */
public static native @Cast("const char*") BytePointer sdxGetOutputName(@Const sdx_context_t context, @Cast("int32_t") int output_index);

/**
 * Borrow a host-readable, C-contiguous output produced by the most recent
 * successful sdxRunAllocating() or sdxRun(). The runtime fills out_tensor;
 * its data and shape pointers remain valid until the next run on this context
 * or until the context is destroyed. Callers must not free either pointer.
 */
public static native @Cast("sdx_status_t") int sdxGetOutputTensor(
    sdx_context_t context,
    @Cast("int32_t") int output_index,
    sdx_tensor_view_t out_tensor);

// #ifdef __cplusplus
// #endif

// #endif  // LIBND4J_DSP_RUNTIME_C_H


}
